name: Run Playwright tests

on:
  push:
    branches: [ 'main' ]

jobs:
  front-end-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy

    env:
      TRAFIKVERKET_API_KEY: ${{ secrets.TRAFIKVERKET_API_KEY }}
      DSN: ${{ secrets.DSN }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd frontend
        npm install
        npx playwright install --with-deps

    - run: |
        cd backend
        npm install

    - run: |
        cd frontend
        npm run e2e
