name: Run Playwright tests

on:
  push:
    branches: [ 'main' ]

jobs:
  front-end-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy

    env:
      TRAFIKVERKET_API_KEY: 2441d9b828c4451587ba46d3b4e8dbd9
      # DSN: mongodb+srv://marjul2023:dFlB4s5itFubhxIT@testcluster.mnw8jji.mongodb.net/

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd frontend
        npm install

    - run: |
        cd backend
        npm install

    - run: |
        cd frontend
        npm run e2e
