name: Run Vitest

on:
  push:
    branches:
      - main

jobs:
  front-end-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
        
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd vue-project-j
        npm install

    - run: |
        cd backend
        npm install

    - run: |
        cd backend
        npm run dev &
      
    - run: sleep 5

    - run: |
        cd vue-project-j
        npm run unittest
