name: Run Vitest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vitest-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

   env:
      VITE_URL: ${{ secrets.VITE_URL }}

    steps:
        
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd frontend
        npm install

    - run: |
        cd backend
        npm install

    - run: |
        cd backend
        npm run dev &
      
    - run: sleep 5

    - run: |
        cd frontend
        npm run unittest
